[opener]
edit = [
  { run = 'nvim "$@"', desc = "Neovim", block = true, for = "unix" }
]
libreoffice = [
  { run = 'libreoffice "$@"', desc = "LibreOffice", orphan = true, for = "unix" }
]

vlc = [
  { run = 'vlc "$@"', desc = "VLC", orphan = true, for = "unix" }
]

brave = [
  { run = 'brave-browser "$@"', desc = "Brave Browser", orphan = true, for = "unix" }
]

gwenview = [
  { run = 'gwenview "$@"', desc = "Gwenview", orphan = true, for = "unix" }
]

[open]
prepend_rules = [
  { mime = "image/*", use = "gwenview" },
  { name = "*.png",   use = "gwenview" },
  { name = "*.jpg",   use = "gwenview" },
  { name = "*.jpeg",  use = "gwenview" },

  { mime = "video/*", use = "vlc" },
  { name = "*.mp4",   use = "vlc" },

  { mime = "application/pdf", use = "brave" },
  { name = "*.pdf",            use = "brave" },

  { name = "*.csv", use = [ "edit", "libreoffice" ] },
  { mime = "text/csv", use = [ "edit", "libreoffice" ] }
]

[[open.rules]]
mime = "text/*"
use = "edit"
[[open.rules]]
name = "*"
use = "edit"
only = true

[mgr]
linemode = "size"
show_hidden = true

